### ISSUE TITLE
Excessive string concatination in debug message

### ISSUE THREAD

**Issue by odewdney** [newrelic/newrelic-android-agent#139]
https://github.com/newrelic/newrelic-android-agent/blob/fec4c538316b83c318ca9fdb0e9d77bc16294994/agent/src/main/java/com/newrelic/agent/android/NewRelic.java#L471C14-L471C14

Should this logging.debug call be wrapped in an if logging.level >= DEBUG

**Comment by odewdney** [comment]
yes, hence the description of "excessive" - a large amount of string manipulation is done, only for it to typically be thrown away as the user is typically not logging at debug level, for a public method that could be called with high frequency. ( 1000s/sec )

i dont think an optimiser could skip the work, as the level value could change by another thread while it was doing the concatenations, and change the outcome.

**Comment by ywang-nr** [comment]
Create a story in backlog to pickup [here](https://new-relic.atlassian.net/browse/NR-180972)
