### ISSUE TITLE
Generated R8 Mapping File cannot be uploaded to google play console with version 7.1.0

### ISSUE THREAD

**Issue by yanneck-blg** [newrelic/newrelic-android-agent#141]
When upgrading from version `7.0.0` of the newrelic-android-agent to version `7.1.0` the Google Play Console can no longer receive the mapping file from the generated `.aab` file. Additionally, when trying to manually set the generated `mapping.txt` file in the console, the Google Play console shows an error. 

I don't know what causes this, but when I verified that when downgrading to `implementation 'com.newrelic.agent.android:android-agent:7.0.0'` again, the re-tracing file automatically gets picked up again from the play console.

**Comment by yanneck-blg** [comment]
Unfortunately, I can't provide a sample project based on the project in which this error occurred. Still, the assumption is that trying to reproduce this error should be possible with a random project that uses `com.newrelic.agent.android:android-agent:7.1.0`. Of course, you'd need to have a project set up in Google Play to verify this. What kind of debug logs could help you?

To clarify: The mapping file indeed gets generated. In my output folder, I have the regular `outputs/mapping` and `outputs/bundle` directories with the expected content. But when creating a new release in the Google Play Console, and trying to assign the `mapping.txt` file from the `outputs/mapping` directory to an uploaded `.aab` file, the upload dialog shows a generic error.

However, when generating an `.aab` file, the console usually automatically picks the re-tracing (`mapping.txt`) file directly from the `.aab` file without further interaction. This is impossible with version `7.1.0` of the newrelic `android-agent`. When I downgrade to version `7.0.0` and upload once again to the console, the mapping file successfully gets picked up again.

I think some weird stuff must be added to the `mapping.txt` file by the plugin so that the Google Play console can no longer detect it as a valid re-tracing file, or something must be wrong with the `.aab` file itself.

**Comment by ndesai-newrelic** [comment]
@yanneck-blg I tried serval times to generate aab file and able to see mapping.txt in .aab bundle explorer  download section. 
<img width="1390" alt="Screenshot 2023-10-17 at 8 42 29 AM" src="https://github.com/newrelic/newrelic-android-agent/assets/89222514/2cb06602-760f-4471-b29e-b88d968d5ec4">

**Comment by ywang-nr** [comment]
Close issue due to no action needed, can reopen as necessary.
