### ISSUE TITLE
`excludePackageInstrumentation` Method Not Working as Expected

### ISSUE THREAD

**Issue by apurvCoin** [newrelic/newrelic-android-agent#156]
I'm experiencing an issue with the excludePackageInstrumentation method in the New Relic Android Agent. Despite specifying package names to exclude from instrumentation, it appears that the method is not functioning correctly. This issue is causing conflicts, particularly with the OkHttp3 library and Salesforce SDK in my project.

Steps to Reproduce:

Implement the excludePackageInstrumentation method in the Gradle build script.
Specify packages to exclude, such as 'com.testapp', 'org.bouncycastle.crypto'.
Run the application and observe that the specified packages are still being instrumented.

Expected Behavior:
Packages specified in the excludePackageInstrumentation method should be excluded from New Relic's instrumentation process.

Actual Behavior:
Specified packages are not being excluded, leading to conflicts and errors, particularly with OkHttp3 and Salesforce SDK.

Environment:

New Relic Android Agent version:7.2.0 and 1.3.3 (RN)
OkHttp3 version: 4.xx and 2.x.x (tried both ) 
Salesforce SDK version: com.salesforce.service:messaging-inapp-ui:1.4.0
Android Studio version:Android Studio Flamingo | 2022.2.1 Patch 1
Build Tools version: 30+

**Comment by cthomas-newrelic** [comment]
@apurvCoin This sounds like an issue we're investigating through our support channel. If it is the same it should have the supporting artifacts we request for every issue. There seems to be a lot of crosstalk around this subject, so the short-version is the crash is a due to an API collision between our agent and implementation of the OkHttp package used by the Saleforce SDK. This work is currently active, so we hope to have a resolution soon.

**Comment by apurvCoin** [comment]
@cthomas-newrelic 

> @apurvCoin This sounds like an issue we're investigating through our support channel. If it is the same it should have the supporting artifacts we request for every issue. There seems to be a lot of crosstalk around this subject, so the short-version is the crash is a due to an API collision between our agent and implementation of the OkHttp package used by the Saleforce SDK. This work is currently active, so we hope to have a resolution soon.

Appreciate the acknowledgment this is the same issue . https://github.com/square/okhttp/pull/7728#issuecomment-1833937055 . It would really help if i can have some quick workaround ,like  Forking the Agent Repo  tinkering with `okHttp3Instrumentation`  class  , or might be  Http3.Call and Request class in our Code itself . Do we have any way to Disable distributed tracing

**Comment by cthomas-newrelic** [comment]
Closing this issue. The method does work as expected, but expectation weren't correct. Apply this plugin config and the offending class will be ignored (and not crash), at teh cost of losing some instrumentaiton.
