### ISSUE TITLE
Can't build project when exclude bcprov-jdk15to18 library

### ISSUE THREAD

**Issue by ilya-savinkov** [newrelic/newrelic-android-agent#189]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I excluded bcprov-jdk15to18 library, because I had duplicated classes between bcprov-jdk15to18 and bcprov-jdk18on libraries in my project. After that I can't make release build, because it is failed with exception from proguard.

## Steps to Reproduce
1) Include library with bcprov-jdk15to18 dependency like stripe.
```kotlin
implementation("com.stripe:stripe-android:20.39.0")
``` 

2) Inclide library with bcprov-jdk18on dependency like sumsub.
```kotlin
implementation("com.sumsub.sns:idensic-mobile-sdk:1.29.0")
```

3) Exclude bcprov-jdk15to18 library
```kotlin
android {
    configurations {
        all {
            exclude(group = "org.bouncycastle", module = "bcprov-jdk15to18")
        }
    }
}
``` 

4) Make release build with R8

## Expected Behavior

You can make release build with R8

## Relevant Logs / Console output
```
* What went wrong:
Execution failed for task ':app:minifyStageGlobalReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin:
        app/build/intermediates/classes/stageGlobalRelease/ALL/
        newrelicTransformClassesForStageGlobalRelease/classes.jar:org
        /bouncycastle/asn1/bsi/BSIObjectIdentifiers.class
``` 

## Your Environment

Newrelic version is 7.3.0

**Comment by cthomas-newrelic** [comment]
@ilya-savinkov Thank you for your submission. We are currently researching this issue, and trying to get a patch out as soon as possible. The crux of the problem is manifest merging during instrumentation.

**Comment by cthomas-newrelic** [comment]
@ilya-savinkov Have you verified that, with this Gradle configuration exclusion, the build is successful without the NR agent?

**Comment by ilya-savinkov** [comment]
@cthomas-newrelic Ыгку, if I remove newrelic plugin, build is built successfully

**Comment by thiago-youx** [comment]
I'm also having this issue when using NR version 7.2.1 or higher, version 7.2.0 still works.

My problem is with the "org.bouncycastle:bcpkix-jdk15on" dependency.

```
* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /home/thiago.you/AndroidStudioProjects/rentcars/app/build/intermediates/classes/release/ALL/newrelicTransformClassesForRelease/classes.jar:org/bouncycastle/LICENSE.class

[...]

Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.internal.vc: Invalid empty classfile]
```

I can build the project when using this dependency version:
```
implementation 'org.bouncycastle:bcpkix-jdk15on:1.52'
```
Any version from this lib different from `1.52` breaks the build with NR.

**Comment by cthomas-newrelic** [comment]
@ilya-savinkov If you are comfortable building the agent, we have a [branch](https://github.com/newrelic/newrelic-android-agent/tree/feature/nr215504-jarMetaINFRewriting) that should address this issue.

**Comment by PositiveThinksNegative** [comment]
I'm having the same issue here
