### ISSUE TITLE
ANR com.newrelic.agent.android.ndk.ANRMonitor.anrMonitorRunner$lambda-1

### ISSUE THREAD

**Issue by sean5940** [newrelic/newrelic-android-agent#198]
There is a high frequency of ANR (Application Not Responding) issues being reported in the Android app currently deployed. Interestingly, these issues are only reported to occur on Android 13.

[information]
OS: Android 13

[attachment]
[stacktrace.txt](https://github.com/newrelic/newrelic-android-agent/files/14986415/stacktrace.txt)

**Comment by ndesai-newrelic** [comment]
@SungilJung can you update latest android and ndk agent?

**Comment by ywang-nr** [comment]
Close the issue and reopen as necessary.
