### ISSUE TITLE
Play Store Rejection: Installed Application information

### ISSUE THREAD

**Issue by appsandwich** [newrelic/newrelic-android-agent#257]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Apologies if this is filed under the wrong category.

We recently received notice from Google that our app update is in violation of Play Store policy, due to collection of Installed Application information being sent to New Relic.

> APK REQUIRES PROMINENT DISCLOSURE​
Your app is not compliant with the [User Data](https://support.google.com/googleplay/android-developer/answer/9888076) and [Mobile Unwanted Software](https://support.google.com/googleplay/android-developer/answer/9970222) policies. Your app is uploading users' Installed Application information to https://mobile-collector.newrelic.com/ without a prominent disclosure.

<img width="777" alt="image" src="https://github.com/user-attachments/assets/9fdf4203-fc18-4ff3-91ff-11b9cd1f3c70">

Google are asking us to present the user with additional UI to prompt the user to agree to the collection of this data by New Relic.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

- Install and initialise New Relic Android agent.
- Submit APK to Google Play Store.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

- New Relic passes the `Installed Application information` check, or the SDK allows the ability to disable/modify the collection of this information.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Android NR agent v7.3.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by JustinRush-NR** [comment]
@appsandwich The New Relic Mobile SDK itself does not collect any information about apps installed. It's possible your app's instrumentation is collecting some information about other installations and reporting them via New Relic, but the SDK itself will only collect telemetry about the app in which it is included.

**Comment by appsandwich** [comment]
> It's possible your app's instrumentation is collecting some information about other installations and reporting them via New Relic

Thanks for the quick reply @JustinRush-NR  

Re: the quoted text, would you mind elaborating a little on this? The only other instrumentation we're using is Firebase Crashlytics, and we're not collecting this information ourselves, so I'm at a loss as to how this information would end up being reported to NR.

**Comment by JustinRush-NR** [comment]
It's difficult to guess without more information. The only concrete detail in the message is a reference to our mobile collector, but that's just the endpoint all telemetry from the New Relic agent is sent to. The agent won't collect anything about other applications unless it is explicitly configured to do so. There are no methods available in the SDK to directly facilitate collecting data about any other application.

**Comment by appsandwich** [comment]
Thanks, appreciate the info. I've spent some time inspecting the traffic coming from our app and I don't see anything that would resemble the data that Google are claiming we're sending. I suspect it's a false positive on their end, so we'll have to try and appeal the rejection.
