### ISSUE TITLE
Unable to upgrade JAVA JDK in my project due to "NewRelic Sdk". As it is STOP logging the traces in account DashBoard when upgrade JDK from 17 to 22.

### ISSUE THREAD

**Issue by PratyeshSingh** [newrelic/newrelic-android-agent#259]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I am unable to upgrade JAVA JDK (from 17 to 22) in my project due to NewRelic Sdk. As in this SDK it STOP working/logging the traces in account DashBoard.

### TIP
- > Task :app:newrelicTransformClassesForDebug
[InvocationDispatcher] Class[unknown] ignored: JDK not supported
[InvocationDispatcher] Class[unknown] ignored: JDK not supported
[InvocationDispatcher] Class[unknown] ignored: JDK not supported
- > Configure project :app
The New Relic plugin may not be compatible with Android Gradle plugin version 8.5.1.
AGP versions 7.0.0 - 8.4 are officially supported.
Set property 'newrelic.warning.agp=false' to disable this warning.
Set property 'newrelic.halt-on-warning=true' to treat warnings as fatal errors.
AGPBI: {"kind":"warning","text":"Accessing value buildConfigFields in variant debug has no effect as the feature buildConfig is disabled.","sources":[{}]}
AGPBI: {"kind":"warning","text":"Accessing value buildConfigFields in variant release has no effect as the feature buildConfig is disabled.","sources":[{}]}

## Steps to Reproduce
- Demo integration [sample can be found here](https://github.com/PratyeshSingh/NewRelicDemo)

## Expected Behavior
- It should keep working with existing task.
- It should allow other application to upgrade there JAVA JDK versions.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )
![Screenshot 2024-07-31 at 2 58 06 PM](https://github.com/user-attachments/assets/8d7307fb-0846-4101-86ed-ede0af669cd7)

## Your Environment
- NewRelic Android agent '7.4.1' ([agent details](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/android-release-notes/))
- using kotlin  version "2.0.0" (i.e. `org.jetbrains.kotlin.android` & `org.jetbrains.kotlin.plugin.compose`)
- AndroidGradlePlugin version "8.5.1"
- JAVA JDK version 22 ( it only working till JDK 17 )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by PratyeshSingh** [comment]
@cthomas-newrelic @ywang-nr 

This should be a quick fix considering the Past Pull-Request. But not sure about complexity if some BOLCER are here.

**Comment by ywang-nr** [comment]
@PratyeshSingh We have work lined up for verifying upgrade agent to JAVA21+, no ETA at the moment but will keep this issue posted with updates.

**Comment by PratyeshSingh** [comment]
@ndesai-newrelic any update on this ?

**Comment by ywang-nr** [comment]
We will have a release coming in the next few weeks. Thanks.

**Comment by ywang-nr** [comment]
v7.6.0 is released. You can find the detailed release notes [here](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/android-release-notes/android-760/).
